[package]
name = "libospl"
version = "0.2.0"
edition = "2021"

[lib]
name = "ospl"
path = "src/ospl.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
rusqlite = { version = "0.32", features = ["bundled", "chrono"] }
rand = "0.8"
infer = "0.16"
chrono = "0.4"
image = "0.25"
log = "0.4"
kamadak-exif = "0.5"

[dependencies.xxhash-rust]
version = "0.8"
features = ["xxh3"]
