version: 2.1
orbs:
    windows: circleci/windows@5
jobs:
  build-linux:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run: cargo test
  build-windows:
    executor: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - choco-cache-1
      - run: choco install rust -y
      - run: choco install mingw -y
      - run: cargo fetch
      - save_cache:
          key: choco-cache-1
          paths:
            - C:\ProgramData\chocolatey\bin
            - c:\programdata\chocolatey\lib
      - run: cargo test
workflows:
  version: 2
  builds:
    jobs:
      - build-linux
      - build-windows
